spring:
  boot:
    admin:
      client:
        url: http://localhost:8093
        username: admin
        password: admin
        auto-registration: true
        instance:
          metadata:
            user:
              name: admin
              password: admin
  application:
    name: Spring Boot Admin Client
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  doc: http://spring.io
server:
  port: 8081